#!/usr/bin/env php
<?php
/* Required Files, Donot Changes Anything */
require __DIR__ . '/system/helper.php';
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \System\Cli\Panther\Commands\ControllerCommand);
$application->add(new \System\Cli\Panther\Commands\ModelCommand);
$application->add(new \System\Cli\Panther\Commands\MigrationCommand);
$application->add(new \System\Cli\Panther\Commands\MigrateCommand);
$application->add(new \System\Cli\Panther\Commands\MigrateRollbackCommand);

$application->run();
